"""fix_profile_item_structure

Revision ID: 485eeba175e3
Revises: 2681575163c0
Create Date: 2025-07-02 06:38:32.093632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '485eeba175e3'
down_revision = '2681575163c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the lesson: 0-delete ,1-publish,2-draft',
               existing_comment='Status of the lesson',
               existing_nullable=False)

    with op.batch_alter_table('profile_item', schema=None) as batch_op:
        batch_op.alter_column('updated',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='Update time')
        batch_op.alter_column('profile_check_prompt',
               existing_type=mysql.TEXT(),
               nullable=False,
               server_default='',
               existing_comment='Profile check prompt')
        batch_op.alter_column('profile_check_model',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=False,
               server_default='',
               existing_comment='Profile check model')
        batch_op.alter_column('profile_check_model_args',
               existing_type=mysql.TEXT(),
               nullable=False,
               server_default='',
               comment='Profile check model args',
               existing_comment='profile_check_model_args')
        batch_op.alter_column('profile_prompt_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='',
               existing_nullable=False)

    with op.batch_alter_table('profile_item_i18n', schema=None) as batch_op:
        batch_op.alter_column('conf_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='',
               existing_nullable=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # 删除 profile_color 字段（如果存在）
    try:
        op.drop_column('profile_item', 'profile_color')
    except:
        pass  # 字段不存在时忽略错误

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('profile_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('profile_item_i18n', schema=None) as batch_op:
        batch_op.alter_column('conf_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='',
               existing_nullable=False)

    with op.batch_alter_table('profile_item', schema=None) as batch_op:
        batch_op.alter_column('profile_prompt_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='',
               existing_nullable=False)
        batch_op.alter_column('profile_check_model_args',
               existing_type=mysql.TEXT(),
               nullable=True,
               comment='profile_check_model_args',
               existing_comment='Profile check model args')
        batch_op.alter_column('profile_check_model',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=True,
               existing_comment='Profile check model')
        batch_op.alter_column('profile_check_prompt',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='Profile check prompt')
        batch_op.alter_column('updated',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_comment='Update time')

    with op.batch_alter_table('ai_lesson', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Status of the lesson',
               existing_comment='Status of the lesson: 0-delete ,1-publish,2-draft',
               existing_nullable=False)

    # ### end Alembic commands ###
