"""user role

Revision ID: 568b8475adab
Revises: 7cee4b561f30
Create Date: 2025-06-21 03:41:16.240547

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "568b8475adab"
down_revision = "7cee4b561f30"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_admin", sa.Boolean(), nullable=False, comment="is admin")
        )
        batch_op.add_column(
            sa.Column("is_creator", sa.Boolean(), nullable=False, comment="is creator")
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.drop_column("is_creator")
        batch_op.drop_column("is_admin")
    # ### end Alembic commands ###
